# 编码器
encoder_conf:
  encoder_name: 'ConformerEncoder'
  encoder_args:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: 'conv2d'
    normalize_before: True
    cnn_module_kernel: 15
    use_cnn_module: True
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'

# 解码器
decoder_conf:
  decoder_name: 'BiTransformerDecoder'
  decoder_args:
    attention_heads: 4
    linear_units: 1024
    num_blocks: 3
    r_num_blocks: 3
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
  model: 'ConformerModel'
  model_args:
    streaming: True
    ctc_weight: 0.3
    lsm_weight: 0.1
    reverse_weight: 0.3
    length_normalized_loss: false
    if_use_nar: True

dataset_conf:
  dataset:
    min_duration: 0.5
    max_duration: 30
    sample_rate: 16000
    use_dB_normalization: True
    target_dB: -20
    manifest_type: 'txt'
  batch_sampler:
    batch_size: 32
    sortagrad: True
    drop_last: True
    shuffle: True
  dataLoader:
    num_workers: 16
  train_manifest: 'librispeech/manifest.train.jsonl'
  test_manifest: 'librispeech/manifest.dev.jsonl'
  mean_istd_path: 'librispeech/mean_istd.json'

preprocess_conf:
  feature_method: 'fbank'
  method_args:
    num_mel_bins: 80

tokenizer_conf:
  vocab_model_dir: "Comformer_Librispeech/dataset/vocab_model/"
  model_type: 'unigram'
  build_vocab_size: 5000
  hard_vocab_limit: False
  byte_fallback: True
  non_linguistic_symbols: [ ]
  remove_non_linguistic_symbols: False

optimizer_conf:
  optimizer: 'Adam'
  optimizer_args:
    lr: 0.0001
    weight_decay: !!float 1.e-6
  scheduler: 'WarmupLR'
  scheduler_args:
    warmup_steps: 25000
    min_lr: 1.e-5

train_conf:
  enable_amp: True
  use_compile: False
  grad_clip: 5.0
  accum_grad: 4
  max_epoch: 20
  freeze_decoder_epochs: 10
  log_interval: 1000
